language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
    allow_failures:
        - php: nightly

sudo: false

before_install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "fxp/composer-asset-plugin:~1.4"

install:
  - travis_retry composer dump-autoload
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mkdir assets
  - cp tests/data/slickConfig.php  /home/travis/build/slickConfig.php
  - cp tests/data/slickConfig.json  /home/travis/build/slickConfig.json
  - mysql -e 'create database myapp_test;'
  - mysql -u root myapp_test < tests/data/sql/1.0.0.sql

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --configuration travis.phpunit.xml
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then PHPUNIT_FLAGS="--coverage-clover coverage.xml"; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then travis_retry php vendor/bin/coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)